### ISSUE TITLE
Discovery: Incident Response Plan - Responses and Response Tools

### ISSUE THREAD

**Issue by TroyA6** [department-of-veterans-affairs/content-build#1322]
Discovery: 
As a Helpdesker, I need to know how to respond to a variety of 'incidents' of different types and severities so that editors and other impacted users can be notified appropriately, and in a timely manner.

This response may include (but is not limited to):

Identify the incident: Type, Impact, Severity, affected audience

Devise response: Communicate appropriate message to appropriate Team for resolution, and appropriate audience for information / status / updates

Response tools: Identify potential tools such as VA.GOV email, Phone Tree, etc. based on incident type/severity/audience

**Comment by EWashb** [comment]
@TroyA6 when you're ready you can add your Mural here and close this ticket!

**Comment by TroyA6** [comment]
Created initial Mural as a visual guide for Incident Response; this guide outlines the incident response timeline in six major steps: Identify Incident, Confirm Incident, Identify impacted teams, Notify those teams, Incident Resolution, Resolution Notification; Notification tools include email, site wide alerts, phone trees, etc. NOTE: this is an early iteration and is subject to change/revision based on conversations, changing situations, etc.
